<?php
/* Questa classe permette di reversare i BBCode in codice HTML */
function bbcode($txt) {
$cerca_codice= array(
'/\[b\](.*?)\[\/b\]/is',
'/\[i\](.*?)\[\/i\]/is',
'/\[u\](.*?)\[\/u\]/is',
'/\[s\](.*?)\[\/s\]/is',
'/\[color\=(.*?)\](.*?)\[\/color\]/is',
'/\[url\=(.*?)\](.*?)\[\/url\]/is',
'/\[spoiler\](.*?)\[\/spoiler\]/is',
'/\[img\](.*?)\[\/img\]/is',
'/\[img width\=(.*?) height\=(.*?)\](.*?)\[\/img\]/is',
'/\[center](.*?)\[\/center\]/is',
'/\[right](.*?)\[\/right\]/is',
'/\[left](.*?)\[\/left\]/is',
'/\[summary](.*?)\[\/summary\]/is',
'/\[br]/is',
'/\[code\](.*?)\[\/code\]/is',
'/\[quote](.*?)\[\/quote\]/is',
'/\[nervoso\]/is',
'/\[preoccupato\]/is',
'/\[sorridente\]/is',
'/\[lingua\]/is',
'/\[felice\]/is',
'/\[occhiolino\]/is',
'/\[V\]/is',
'/\[fg\]/is',
'/\[riot\]/is',
'/\[addit\]/is',
'/\[pwn\]/is',
'/\[zxc\]/is',
'/\[argh\]/is',
'/\[look\]/is',
'/\[pazzo\]/is',
'/\[guru\]/is',
'/\[sisi\]/is',
'/\[nono\]/is',
'/\[ert\]/is',
'/\[rotfl\]/is',
);
$sostituisci_codice = array(
'<b>$1</b>',
'<i>$1</i>',
'<u>$1</u>',
'<s>$1</s>',
'<font color="$1">$2</font>',
'<a href="$1">$2</a>',
'<a onclick="Spoiler();">Mostra/Nascondi</a><div class="spoiler">$1</div>',
'<img src="$1">',
'<a href="$3"><img src="$3" width="$1" height="$2"></a>',
'<p align="center">$1</p>',
'<p align="right">$1</p>',
'<p align="left">$1</p>',
'<h2>$1</h2>',
'<br />',
'<textarea style="border: 0px; overflow: auto; width:100%;" rows="8">$1</textarea>',
'<blockquote><span>$1</span></blockquote>',
'<img src="/swanp/wysiwyg/emoticons/nervoso.gif">',
'<img src="/swanp/wysiwyg/emoticons/preoccupato.gif">',
'<img src="/swanp/wysiwyg/emoticons/sorridente.gif">',
'<img src="/swanp/wysiwyg/emoticons/lingua.gif">',
'<img src="/swanp/wysiwyg/emoticons/felice.gif">',
'<img src="/swanp/wysiwyg/emoticons/occhiolino.gif">',
'<img src="/swanp/wysiwyg/emoticons/V.gif">',
'<img src="/swanp/wysiwyg/emoticons/fg.gif">',
'<img src="/swanp/wysiwyg/emoticons/riot.gif">',
'<img src="/swanp/wysiwyg/emoticons/addit.gif">',
'<img src="/swanp/wysiwyg/emoticons/pwn.gif">',
'<img src="/swanp/wysiwyg/emoticons/zxc.gif">',
'<img src="/swanp/wysiwyg/emoticons/argh.gif">',
'<img src="/swanp/wysiwyg/emoticons/look.gif">',
'<img src="/swanp/wysiwyg/emoticons/pazzo.gif">',
'<img src="/swanp/wysiwyg/emoticons/guru.gif">',
'<img src="/swanp/wysiwyg/emoticons/sisi.gif">',
'<img src="/swanp/wysiwyg/emoticons/nono.gif">',
'<img src="/swanp/wysiwyg/emoticons/ert.png">',
'<img src="/swanp/wysiwyg/emoticons/rotfl.gif">',
);
$txt= preg_replace ($cerca_codice, $sostituisci_codice, $txt);
return $txt;
}

function bbcodecommenti($testo) {
$cerca_codice= array(
'/\[b\](.*?)\[\/b\]/is',
'/\[i\](.*?)\[\/i\]/is',
'/\[u\](.*?)\[\/u\]/is',
'/\[s\](.*?)\[\/s\]/is',
'/\[color\=(.*?)\](.*?)\[\/color\]/is',
'/\[url\=(.*?)\](.*?)\[\/url\]/is',
'/\[spoiler\](.*?)\[\/spoiler\]/is',
'/\[center](.*?)\[\/center\]/is',
'/\[right](.*?)\[\/right\]/is',
'/\[left](.*?)\[\/left\]/is',
'/\[br]/is',
'/\[code\](.*?)\[\/code\]/is',
'/\[quote](.*?)\[\/quote\]/is',
'/\[nervoso\]/is',
'/\[preoccupato\]/is',
'/\[sorridente\]/is',
'/\[lingua\]/is',
'/\[felice\]/is',
'/\[occhiolino\]/is',
'/\[V\]/is',
'/\[fg\]/is',
'/\[riot\]/is',
'/\[addit\]/is',
'/\[pwn\]/is',
'/\[zxc\]/is',
'/\[argh\]/is',
'/\[look\]/is',
'/\[pazzo\]/is',
'/\[guru\]/is',
'/\[sisi\]/is',
'/\[nono\]/is',
'/\[ert\]/is',
'/\[rotfl\]/is',
);
$sostituisci_codice = array(
'<b>$1</b>',
'<i>$1</i>',
'<u>$1</u>',
'<s>$1</s>',
'<font color="$1">$2</font>',
'<a href="$1">$2</a>',
'<a onclick="Spoiler();">Mostra/Nascondi</a><div class="spoiler">$1</div>',
'<p align="center">$1</p>',
'<p align="right">$1</p>',
'<p align="left">$1</p>',
'<br />',
'<textarea style="border: 0px; overflow: auto; width:100%;" rows="8">$1</textarea>',
'<blockquote><span>$1</span></blockquote>',
'<img src="/swanp/wysiwyg/emoticons/nervoso.gif">',
'<img src="/swanp/wysiwyg/emoticons/preoccupato.gif">',
'<img src="/swanp/wysiwyg/emoticons/sorridente.gif">',
'<img src="/swanp/wysiwyg/emoticons/lingua.gif">',
'<img src="/swanp/wysiwyg/emoticons/felice.gif">',
'<img src="/swanp/wysiwyg/emoticons/occhiolino.gif">',
'<img src="/swanp/wysiwyg/emoticons/V.gif">',
'<img src="/swanp/wysiwyg/emoticons/fg.gif">',
'<img src="/swanp/wysiwyg/emoticons/riot.gif">',
'<img src="/swanp/wysiwyg/emoticons/addit.gif">',
'<img src="/swanp/wysiwyg/emoticons/pwn.gif">',
'<img src="/swanp/wysiwyg/emoticons/zxc.gif">',
'<img src="/swanp/wysiwyg/emoticons/argh.gif">',
'<img src="/swanp/wysiwyg/emoticons/look.gif">',
'<img src="/swanp/wysiwyg/emoticons/pazzo.gif">',
'<img src="/swanp/wysiwyg/emoticons/guru.gif">',
'<img src="/swanp/wysiwyg/emoticons/sisi.gif">',
'<img src="/swanp/wysiwyg/emoticons/nono.gif">',
'<img src="/swanp/wysiwyg/emoticons/ert.png">',
'<img src="/swanp/wysiwyg/emoticons/rotfl.gif">',
);
$testo= preg_replace ($cerca_codice, $sostituisci_codice, $testo);
return $testo;
}
?>
